Currencies={
"Afghan Afghani (AFN)"                      : "AFN",
"United Arab Emirates Dirham (AED)"         : "AED",
"Albanian Lek (ALL)"                        : "ALL",
"Armenian Dram (AMD)"                       : "AMD",
"Netherlands Antillean Guilder (ANG)"       : "ANG",
"Angolan Kwanza (AOA)"                      : "AOA",
"Argentine Peso (ARS)"                      : "ARS",
"Australian Dollar (A$)"                    : "AUD",
"Aruban Florin (AWG)"                       : "AWG",
"Azerbaijani Manat (AZN)"                   : "AZN",
"Bosnia-Herzegovina Convertible Mark (BAM)" : "BAM",
"Barbadian Dollar (BBD)"                    : "BBD",
"Bangladeshi Taka (BDT)"                    : "BDT",
"Bulgarian Lev (BGN)"                       : "BGN",
"Bahraini Dinar (BHD)"                      : "BHD",
"Burundian Franc (BIF)"                     : "BIF",
"Bermudan Dollar (BMD)"                     : "BMD",
"Brunei Dollar (BND)"                       : "BND",
"Bolivian Boliviano (BOB)"                  : "BOB",
"Brazilian Real (R$)"                       : "BRL",
"Bahamian Dollar (BSD)"                     : "BSD",
"Bitcoin (?)"                               : "BTC",
"Bhutanese Ngultrum (BTN)"                  : "BTN",
"Botswanan Pula (BWP)"                      : "BWP",
"Belarusian Ruble (BYR)"                    : "BYR",
"Belize Dollar (BZD)"                       : "BZD",
"Canadian Dollar (CA$)"                     : "CAD",
"Congolese Franc (CDF)"                     : "CDF",
"Swiss Franc (CHF)"                         : "CHF",
"Chilean Unit of Account (UF) (CLF)"        : "CLF",
"Chilean Peso (CLP)"                        : "CLP",
"CNH (CNH)"                                 : "CNH",
"Chinese Yuan (CNY)"                        : "CNY",
"Colombian Peso (COP)"                      : "COP",
"Costa Rican Colon (CRC)"                   : "CRC",
"Cuban Peso (CUP)"                          : "CUP",
"Cape Verdean Escudo (CVE)"                 : "CVE",
"Czech Republic Koruna (CZK)"               : "CZK",
"German Mark (DEM)"                         : "DEM",
"Djiboutian Franc (DJF)"                    : "DJF",
"Danish Krone (DKK)"                        : "DKK",
"Dominican Peso (DOP)"                      : "DOP",
"Algerian Dinar (DZD)"                      : "DZD",
"Egyptian Pound (EGP)"                      : "EGP",
"Eritrean Nakfa (ERN)"                      : "ERN",
"Ethiopian Birr (ETB)"                      : "ETB",
"Euro (EUR)"                                : "EUR",
"Finnish Markka (FIM)"                      : "FIM",
"Fijian Dollar (FJD)"                       : "FJD",
"Falkland Islands Pound (FKP)"              : "FKP",
"French Franc (FRF)"                        : "FRF",
"British Pound (GBP)"                       : "GBP",
"Georgian Lari (GEL)"                       : "GEL",
"Ghanaian Cedi (GHS)"                       : "GHS",
"Gibraltar Pound (GIP)"                     : "GIP",
"Gambian Dalasi (GMD)"                      : "GMD",
"Guinean Franc (GNF)"                       : "GNF",
"Guatemalan Quetzal (GTQ)"                  : "GTQ",
"Guyanaese Dollar (GYD)"                    : "GYD",
"Hong Kong Dollar (HK$)"                    : "HKD",
"Honduran Lempira (HNL)"                    : "HNL",
"Croatian Kuna (HRK)"                       : "HRK",
"Haitian Gourde (HTG)"                      : "HTG",
"Hungarian Forint (HUF)"                    : "HUF",
"Indonesian Rupiah (IDR)"                   : "IDR",
"Irish Pound (IEP)"                         : "IEP",
"Israeli New Sheqel (?)"                    : "ILS",
"Indian Rupee (Rs.)"                        : "INR",
"Iraqi Dinar (IQD)"                         : "IQD",
"Iranian Rial (IRR)"                        : "IRR",
"Icelandic Krona (ISK)"                     : "ISK",
"Italian Lira (ITL)"                        : "ITL",
"Jamaican Dollar (JMD)"                     : "JMD",
"Jordanian Dinar (JOD)"                     : "JOD",
"Japanese Yen (Y)"                          : "JPY",
"Kenyan Shilling (KES)"                     : "KES",
"Kyrgystani Som (KGS)"                      : "KGS",
"Cambodian Riel (KHR)"                      : "KHR",
"Comorian Franc (KMF)"                      : "KMF",
"North Korean Won (KPW)"                    : "KPW",
"South Korean Won (?)"                      : "KRW",
"Kuwaiti Dinar (KWD)"                       : "KWD",
"Cayman Islands Dollar (KYD)"               : "KYD",
"Kazakhstani Tenge (KZT)"                   : "KZT",
"Laotian Kip (LAK)"                         : "LAK",
"Lebanese Pound (LBP)"                      : "LBP",
"Sri Lankan Rupee (LKR)"                    : "LKR",
"Liberian Dollar (LRD)"                     : "LRD",
"Lesotho Loti (LSL)"                        : "LSL",
"Lithuanian Litas (LTL)"                    : "LTL",
"Latvian Lats (LVL)"                        : "LVL",
"Libyan Dinar (LYD)"                        : "LYD",
"Moroccan Dirham (MAD)"                     : "MAD",
"Moldovan Leu (MDL)"                        : "MDL",
"Malagasy Ariary (MGA)"                     : "MGA",
"Macedonian Denar (MKD)"                    : "MKD",
"Myanmar Kyat (MMK)"                        : "MMK",
"Mongolian Tugrik (MNT)"                    : "MNT",
"Macanese Pataca (MOP)"                     : "MOP",
"Mauritanian Ouguiya (MRO)"                 : "MRO",
"Mauritian Rupee (MUR)"                     : "MUR",
"Maldivian Rufiyaa (MVR)"                   : "MVR",
"Malawian Kwacha (MWK)"                     : "MWK",
"Mexican Peso (MX$)"                        : "MXN",
"Malaysian Ringgit (MYR)"                   : "MYR",
"Mozambican Metical (MZN)"                  : "MZN",
"Namibian Dollar (NAD)"                     : "NAD",
"Nigerian Naira (NGN)"                      : "NGN",
"Nicaraguan Cordoba (NIO)"                  : "NIO",
"Norwegian Krone (NOK)"                     : "NOK",
"Nepalese Rupee (NPR)"                      : "NPR",
"New Zealand Dollar (NZ$)"                  : "NZD",
"Omani Rial (OMR)"                          : "OMR",
"Panamanian Balboa (PAB)"                   : "PAB",
"Peruvian Nuevo Sol (PEN)"                  : "PEN",
"Papua New Guinean Kina (PGK)"              : "PGK",
"Philippine Peso (Php)"                     : "PHP",
"PKG (PKG)"                                 : "PKG",
"Pakistani Rupee (PKR)"                     : "PKR",
"Polish Zloty (PLN)"                        : "PLN",
"Paraguayan Guarani (PYG)"                  : "PYG",
"Qatari Rial (QAR)"                         : "QAR",
"Romanian Leu (RON)"                        : "RON",
"Serbian Dinar (RSD)"                       : "RSD",
"Russian Ruble (RUB)"                       : "RUB",
"Rwandan Franc (RWF)"                       : "RWF",
"Saudi Riyal (SAR)"                         : "SAR",
"Solomon Islands Dollar (SBD)"              : "SBD",
"Seychellois Rupee (SCR)"                   : "SCR",
"Sudanese Pound (SDG)"                      : "SDG",
"Swedish Krona (SEK)"                       : "SEK",
"Singapore Dollar (SGD)"                    : "SGD",
"St. Helena Pound (SHP)"                    : "SHP",
"Slovak Koruna (SKK)"                       : "SKK",
"Sierra Leonean Leone (SLL)"                : "SLL",
"Somali Shilling (SOS)"                     : "SOS",
"Surinamese Dollar (SRD)"                   : "SRD",
"S?o Tome &amp; Principe Dobra (STD)"       : "STD",
"Salvadoran Colon (SVC)"                    : "SVC",
"Syrian Pound (SYP)"                        : "SYP",
"Swazi Lilangeni (SZL)"                     : "SZL",
"Thai Baht (THB)"                           : "THB",
"Tajikistani Somoni (TJS)"                  : "TJS",
"Turkmenistani Manat (TMT)"                 : "TMT",
"Tunisian Dinar (TND)"                      : "TND",
"Tongan Pa?anga (TOP)"                      : "TOP",
"Turkish Lira (TRY)"                        : "TRY",
"Trinidad &amp; Tobago Dollar (TTD)"        : "TTD",
"New Taiwan Dollar (NT$)"                   : "TWD",
"Tanzanian Shilling (TZS)"                  : "TZS",
"Ukrainian Hryvnia (UAH)"                   : "UAH",
"Ugandan Shilling (UGX)"                    : "UGX",
"US Dollar ($)"                             : "USD",
"Uruguayan Peso (UYU)"                      : "UYU",
"Uzbekistani Som (UZS)"                     : "UZS",
"Venezuelan Bolivar (VEF)"                  : "VEF",
"Vietnamese Dong (?)"                       : "VND",
"Vanuatu Vatu (VUV)"                        : "VUV",
"Samoan Tala (WST)"                         : "WST",
"Central African CFA Franc (FCFA)"          : "XAF",
"East Caribbean Dollar (EC$)"               : "XCD",
"Special Drawing Rights (XDR)"              : "XDR",
"West African CFA Franc (CFA)"              : "XOF",
"CFP Franc (CFPF)"                          : "XPF",
"Yemeni Rial (YER)"                         : "YER",
"South African Rand (ZAR)"                  : "ZAR",
"Zambian Kwacha (1968-2012) (ZMK)"          : "ZMK",
"Zambian Kwacha (ZMW)"                      : "ZMW",
"Zimbabwean Dollar (2009) (ZWL)"            : "ZWL"
}